### ISSUE TITLE
bad gateway

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#10]
you probably realize this but just in case you don't :) I'm getting a `Bad Gateway` error right now on http://lolaweb.databio.org

**Comment by nmagee** [comment]
@nsheff are you still getting the app okay with the longer URL http://lolaweb.databio.org/shinyLOLA/ ?

**Comment by nmagee** [comment]
I'm seeing it now too -- browser cache needed clearing. Working to fix it.

**Comment by nmagee** [comment]
We're back up as of 20 mins ago or so, but this was useful, as it exposed a setting I need to adjust -- and need to research a bit more how Traefik maps domain names to the app.

**Comment by nsheff** [comment]
I'm still getting `Bad Gateway` here.

**Comment by nsheff** [comment]
it's  back up for me now

**Comment by nmagee** [comment]
I have hard-coded our domain into the right place in the Traefik config now -- it doesn't go where I would have expected it to.

I'll close this for now.
