### ISSUE TITLE
results redirection fails

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#102]
If you run a job, it says "redirecting to your results" and populates the URL, but the results never show up.

If you then refresh that URL it works, but there's something broken with the redirection.

**Comment by vpnagraj** [comment]
@nsheff weird ... i've tried several runs (each with different input parameters, in safari and chrome) all of which have completed and redirected successfully

can you confirm that you're still seeing the problem with redirection?

**Comment by nsheff** [comment]
Ok on a second try, it worked... so this is intermittent...

**Comment by nsheff** [comment]
maybe just a fluke that one time it didn't go. I'll re-open if it comes back.
