### ISSUE TITLE
Move production stack to DC/OS

### ISSUE THREAD

**Issue by nmagee** [databio/LOLAweb#103]
@vpnagraj @nsheff , I think LOLAweb is ready to port over to DC/OS now. I have a running version here: 

```
http://lolaweb.uvadcos.io/LOLAweb/apps/LOLAweb/
```

DCOS service config file is below. This version seems to be performing nominally. Nathan, could you verify that sometime for us please? (I cannot pull up the sample file link but I believe that's an unrelated error -- I think it got deleted as an "old" file the server trims.)

If performance is fine, then the last update we should make is to reconfigure Shiny to run the LOLAweb app directly instead of having to append the `/LOLAweb/apps/LOLAweb/` path in the URL. (Pete knows how to do this.)

As we get ready to cut over I will copy over any remaining cached files from the current server stack.

```
{
  "env": {
    "LWLOCAL": "/mnt/dcos/lola/",
    "LWREF": "/mnt/qproject/shefflab/LOLAweb/"
  },
  "labels": {
    "HAPROXY_GROUP": "external",
    "HAPROXY_0_VHOST": "lolaweb.uvadcos.io"
  },
  "id": "/shefflab/lolaweb",
  "backoffFactor": 1.15,
  "backoffSeconds": 1,
  "constraints": [
    [
      "@region",
      "IS",
      "uva-udc"
    ]
  ],
  "container": {
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 0,
        "protocol": "tcp",
        "servicePort": 10115
      }
    ],
    "type": "MESOS",
    "volumes": [
      {
        "containerPath": "/mnt/dcos/lola",
        "hostPath": "/mnt/dcos/lola",
        "mode": "RW"
      },
      {
        "containerPath": "/mnt/qproject/shefflab/LOLAweb",
        "hostPath": "/mnt/qproject/shefflab/LOLAweb",
        "mode": "RO"
      }
    ],
    "docker": {
      "image": "databio/lolaweb:latest",
      "forcePullImage": true,
      "parameters": []
    }
  },
  "cpus": 2,
  "disk": 0,
  "healthChecks": [
    {
      "gracePeriodSeconds": 5,
      "ignoreHttp1xx": false,
      "intervalSeconds": 3,
      "maxConsecutiveFailures": 2,
      "portIndex": 0,
      "timeoutSeconds": 2,
      "delaySeconds": 15,
      "protocol": "HTTP",
      "path": "/"
    }
  ],
  "instances": 8,
  "maxLaunchDelaySeconds": 300,
  "mem": 12000,
  "gpus": 0,
  "networks": [
    {
      "mode": "container/bridge"
    }
  ],
  "requirePorts": false,
  "upgradeStrategy": {
    "maximumOverCapacity": 1,
    "minimumHealthCapacity": 1
  },
  "killSelection": "YOUNGEST_FIRST",
  "unreachableStrategy": {
    "inactiveAfterSeconds": 0,
    "expungeAfterSeconds": 0
  },
  "fetch": []
}
```

**Comment by nsheff** [comment]
I think this move has lost the example cache, so the "View example results" link no longer works.

**Comment by vpnagraj** [comment]
@nmagee i know we talked about this yesterday ... 

i went ahead and recreated a cache with the "example data" and defaults

the cache name is `FYDO25QB4HUK6E1` can you rename that cache to be `F1NJU8KSWI59H4E` (name associated with current "sample results" link)

if that's an issue i can also just change the sample results link in the code ... but i think it's easier to just rename that file?

**Comment by nsheff** [comment]
When I click on the link now (/?key=F1NJU8KSWI59H4E) it says "disconnected" ...

**Comment by nmagee** [comment]
Yes, this seems like unusual behavior but (I think) it is because I took the cache file Pete suggested, copied it, and renamed to F1NJU8KSWI59H4E.Rdata. Seems Shiny does not like that, thus the “disconnected” error, rather than a “cannot find” error. Perhaps there’s something ID-related within the contents of the R cache file?

**Comment by nsheff** [comment]
the shiny logs will likely tell a more complete story

**Comment by vpnagraj** [comment]
ok so given that renaming the file didn't do the trick, i went ahead and 1) created a new sample cache and 2) changed the link the code

these changes are live (2ddd6d6) and the new cache name is `M2LZOJXEQSKG98A`

http://lolaweb.databio.org/?key=M2LZOJXEQSKG98A

@nmagee i think you mentioned you have script that ignores files to be purged? can you add the file name to that script?

**Comment by nmagee** [comment]
Not possible without disabling WebSockets. Will revisit this when k8s replaces DCOS.
