### ISSUE TITLE
server is offline

### ISSUE THREAD

**Issue by malger** [databio/LOLAweb#105]
404 when i try to connect to our hosted instance

**Comment by nsheff** [comment]
indeed, lolaweb.databio.org is down... @nmagee?

**Comment by nmagee** [comment]
Checking on this now.

**Comment by nmagee** [comment]
It's back online now, @malger @nsheff -- seems the Docker swarm wasn't rebalancing properly. I'll patch those and restart services after hours sometime this week.

**Comment by nmagee** [comment]
@malger thanks for the heads up.
