### ISSUE TITLE
LOLA web front page is disabled

### ISSUE THREAD

**Issue by danasilv** [databio/LOLAweb#107]
Hi LOLA web team,

I love the software and had been using it for awhile. Today the front page is disabled: if you go to http://lolaweb.databio.org/ the page is darkened and you can't choose parameters such as reference genome. 

Thank you, really appreciate this project!

**Comment by nsheff** [comment]
Hi @danasilv 

It's actually working as normal for me... can you try a different browser? I wonder if your connection is just stale or something...

**Comment by danasilv** [comment]
Thank you for the incredibly quick reply!
I tried now from a colleague's computer, who had never used LOLA before,
and got the same screen:
[image: image.png]
It looks almost like always, but some fields are missing.

Thank you,
Dana

**Comment by nsheff** [comment]
Interesting. I may need to look into the error logs...Do you get any error on the console in chrome? (Command + Option + J (Mac) or Control + Shift + J (Windows, Linux, Chrome OS))

**Comment by danasilv** [comment]
I attached it here:
[image: image.png]
Thank you!

**Comment by nsheff** [comment]
Hi, I cannot see your attachment.

**Comment by danasilv** [comment]
![image (11)](https://user-images.githubusercontent.com/32930322/76373555-15d68780-6317-11ea-9cc0-a30529b05c93.png)
attaching again, thanks!

**Comment by nsheff** [comment]
@datasilv -- sorry for not responding to this. @nmagee restarted the containers on the server, can you confirm if the problem is still happening for you?

**Comment by danasilv** [comment]
Everything is working! Thank you!
