### ISSUE TITLE
update sample cache link

### ISSUE THREAD

**Issue by vpnagraj** [databio/LOLAweb#110]
the current link to "Sample Results" in the LOLAweb app points to a cache that no longer exists:

http://lolaweb.databio.org/?key=M2LZOJXEQSKG98A

i've re-generated an example cache (AY86BGRD9EC5Z7T) and updated the 
app to point to it: 

https://github.com/databio/LOLAweb/commit/4eb69284c3264e150aaf2042bc4cb82ed7c02d30

this change will be part of the forthcoming v1.4.0 release and once merged the "Sample Results" link should work properly:

http://lolaweb.databio.org/?key=AY86BGRD9EC5Z7T

@nmagee this expiration of the sample cache has happened previously (see v1.3.1 release notes: https://github.com/databio/LOLAweb/releases/tag/v.1.3.1). im assuming the cache was purged after a certain amount of time to make space on disk. is there a way we can ensure that sample result cache doesnt get removed from disk?

**Comment by nmagee** [comment]
@vpnagraj precisely - the cron task that clears the cache bonked that old file. I thought of exactly how to work around that in the script, but only after it was too late that time. I'll preserve this new example cache going forward.

**Comment by vpnagraj** [comment]
updated the sample cache link in https://github.com/databio/LOLAweb/commit/4eb69284c3264e150aaf2042bc4cb82ed7c02d30

seems to be working for now.

going to close this but @nmagee feel free to reopen if you need track any other changes to preserve the cache moving forward.

**Comment by nmagee** [comment]
Thanks @vpnagraj - yeah I updated the script that clears the cache after 365 days and preserved a copy of the sample cache outside that dir. So it will always place a copy of that back after clearing. Should be all set going forward.
