### ISSUE TITLE
Help text for app interface

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#16]
Make the question marks lead to a popup or something that displays text, instead of going to the R package docs. These are meant to be like little tooltips or something. Here's the text for each:

> The User Set is your set of genomic regions that you want to test for overlap with the database. Upload a file in [BED format](https://genome.ucsc.edu/FAQ/FAQformat.html) (really, it just needs the first 3 columns: `chr`, `start`, and `end`). You can also drag and drop multiple files and they will be analyzed simultaneously!

Universe:
> The universe is your background set of regions. You should think of the universe as the set of regions you tested for possible inclusion in your user sets; or, in other words, it is the restricted background set of regions that were tested, including everything in your regions of interest as well as those that did not get included. We recommend you upload a universe that is specific to the query set, but we also provide a few basic region sets (like tiling regions, or the set of all active DNaseI hypersensitive elements from the ENCODE project). The choice of universe can have a drastic affect on the results of the analysis, so it may also be worth running LOLA few times with different universe sets. For further information, there are more details in the [LOLA documentation](http://code.databio.org/LOLA/articles/choosingUniverse.html).

DB:
> We have provided a few different general-purpose databases. We recommend starting with the Core database, but there are also a few other more specific options if you want to extend your analysis. Further details about what is contained in each database can be found in the [documentation on LOLA region databases](http://databio.org/regiondb).

Finally, we need a link to example results and some documentation on interpretation. So, I suggest putting a link to "Sample results" (which could just take you here: http://lolaweb.databio.org/?key=O1K24SVTQZL5WPJ)

**Comment by vpnagraj** [comment]
the user set, universe and db popovers were added in 4f63e56

@nsheff where do you think we should put the "Sample results" link?

**Comment by nsheff** [comment]
those are beautiful. :trophy:

> @nsheff where do you think we should put the "Sample results" link?

For now I would just stick it under the RUN LOLA button.

I would also make the whole data entry interface (top half) be not present in the results interface. I guess this is part of the 'great division'

**Comment by vpnagraj** [comment]
got it ... sample results under runLOLA button as of 0eb8c87
