### ISSUE TITLE
Tooltips to help with interpretation

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#17]
In the interactive results interface, I think we should also add some tooltips.

"Select Collection":
> LOLA databases are made up of one or more sub-collections of region set. Using this drop-down, you can filter your plots and tables to show only the results from one of these collections at a time.

"Max Rank Cutoff"
> These sliders can be used 

Let's group all 3 plots under a single heading called "LOLA Results", and make the individual plot headings smaller; then we can add a tooltip question mark that says:
> These barplots show the highest-ranking region sets from the database. The higher scores indicate more overlap with your query set. The results are scored using 3 statistics: Support is the raw number of regions that overlapped between your query set and the database set. LogPVal and LogOdds are the results of a Fisher's exact test scoring the significance of that overlap.

> We rank each region set from the database for each of these 3 scores, and you can see the raw scores and the ranks in the table below. You can also see the maximum and mean ranks across all 3 categories.

**Comment by vpnagraj** [comment]
@nsheff can you confirm what you want "Max Rank Cutoff" help text to say?

the rest is implemented in 2448956 and dd36cff

**Comment by nsheff** [comment]
Ah yeah. Looks like I started that and then stopped, whoops. Maybe make a parent heading like "Plot options" or "Display options" or something. Tooltip text:

> These sliders can be used to adjust the number of results displayed on the plots. You may adjust cutoffs for any of the 3 statistics, as well as for the combined maximum rank, which prioritizes region sets that score well in all 3 categories.

Also the "Select Collection" style doesn't match the others.

**Comment by vpnagraj** [comment]
ok i just added "Display Options" above the sliders 7bd9fb2

should be at http://dev.lolaweb.uvasomrc.io/ after the docker build

i also attempted a fix at the selection collection style 2910013 

that said, we may want to rethink and have a parent heading for the collection, sort, userset dropdowns with a single tooltip (to match "Display Options") ... closing for now though

**Comment by nsheff** [comment]
agreed.
