### ISSUE TITLE
'Run Again' button on results page?

### ISSUE THREAD

**Issue by nmagee** [databio/LOLAweb#21]
Would it make sense on a results page to have a button to start over, or run another analysis? I just realized, after getting to http://dev.lolaweb.uvasomrc.io/?key=D1N9IEPLGS5MJOC with sample data, that I didn't have an easy to way to run LOLA again.

**Comment by vpnagraj** [comment]
@nmagee 👍 the relationship between the results "view" and run interface can certainly be improved

that said, there isn't a great way to do this (besides a simple link back to the original url) without a major overhaul of the internal logic

personally i think i should focus on the decoupling instead ... i think we decouple (so there's a `run` app and `results` app) that will solve this issue and generally provide a better UI

stay tuned ... this is part of my "2.0" plan :)

**Comment by nmagee** [comment]
Sounds good.

In the meantime I linked the header LOLAweb image to get you back to the initial page, which is often a reliable shortcut for getting back to the root of a website.

**Comment by vpnagraj** [comment]
re-phrased this in #30 

closing this one out
