### ISSUE TITLE
Consider making "sample results" link a relative URL

### ISSUE THREAD

**Issue by nmagee** [databio/LOLAweb#22]
https://github.com/databio/LOLAweb/blob/32a7c0ad556f0c63962ec12a5f292bed008ba01d/apps/LOLAweb/app.R#L79

A very minor suggestion: I'm not sure if Shiny accepts relative URLs, but if this is changed to a relative path, it will keep you on the respective container (`dev`, `staging`, `latest`).

**Comment by nsheff** [comment]
👍 yeah I thought this as well

**Comment by vpnagraj** [comment]
ok well i can definitely do that (and had considered it too) ... but that will limit the portability for folks who are trying to run the app locally ... that is unless we provide instructions for how to download that sample cache and make it available somewhere?

thoughts?

**Comment by nsheff** [comment]
can it be included in the package? it should be relatively small...

**Comment by vpnagraj** [comment]
cool ... just pushed a fix for the relative url, so i'm going to close this out for now

that said, i think there is a bigger question of making all reference data (and sample caches) available in one place for people ... and documenting how to use `LOLAweb` locally ... will open a separate issue for that
