### ISSUE TITLE
old sample results get broken

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#25]
probably you realize this, but the sample results will stop working if they are old, when you update to the new way of wrapping the results into a list; hence, right now on dev, the link to sample results is failing.

I think this won't be a problem in the future, but once we're settled we need to make sure we preserve backwards compatibility so that old results can still load, even if we add a new figure or something. as long as they're in a list it should be fine; just don't display the image if the cache doesn't contain result for that image (in other words, if the cache was generated for the compute for that image was included in the code)

for now we just have to make sure the "Sample Results" link points to a new-style result when that is ready.

**Comment by vpnagraj** [comment]
@nsheff yeah great point ... i definitely had that mind and was actually going to open an issue here myself

and with this in mind ... do you think we should include any disclaimer or note about cache retention anywhere?

**Comment by vpnagraj** [comment]
fixed in  173fa93

will open a separate issue for the disclaimer documentation
