### ISSUE TITLE
container bloat

### ISSUE THREAD

**Issue by nmagee** [databio/LOLAweb#26]
Not mandatory for the article submission, but if we can get our container to lose a little bit of weight in the nearfuture, that would be great. 

We shot from 1.4GB to nearly 5GB yesterday, so it would make good sense to pull out any reference data/DB's that we can, and put them into the NFS share in one centralized reference location like the other reference data.

**Comment by vpnagraj** [comment]
@nmagee good call ... my vote is to install these reference db packages (and their system deps) to a specific libpath on the host machine ... then mount that location to the containers at run and add the libpath for the shiny server session somewhere in the dockerfile

i can get started on this next week ...

**Comment by nsheff** [comment]
yep, told you this was going to happen -- the other alternative is to make GenomicDistributions require less stuff. I can certainly work on that at some point as well.

but @vpnagraj 's suggestion is exactly what we should do (either way) because that is a generally useful solution to this class of problem, which will recur.

**Comment by nsheff** [comment]
GenomicDistributions also takes 7 seconds to load, which is an issue.

**Comment by nsheff** [comment]
Ok @vpnagraj  please try the new GenomicDistributions v0.3 for this.

**Comment by nsheff** [comment]
Container size is now down around 1.4Gb again, so this appears to have solved it

**Comment by nsheff** [comment]
Should we call this done, or are you still planning to produce a reference database package container to mount separately as a specific libpath? I still think that's a generally useful concept.

**Comment by vpnagraj** [comment]
containers are nice and lean
