### ISSUE TITLE
incorporate `plotFeatureDist`

### ISSUE THREAD

**Issue by vpnagraj** [databio/LOLAweb#28]
the app should include `plotFeatureDist()` from `GenomicDistributions` 

this will require:

1. adding a new object to result list that's cached
2. figuring out parallelization of the `runLOLA` and `featureDistribution` computation ... see [SO post](https://stackoverflow.com/questions/21519431/r-run-2-different-blocks-of-code-at-the-same-time-in-parallel?answertab=votes#tab-top) for example

**Comment by nsheff** [comment]
this function adds 5 minutes ish to the compute time; should we look into ways to reduce that?

**Comment by nsheff** [comment]
I've completely rewritten this function and it is now much, much faster. I also renamed it. Please take a look at the new vignette to see how to do this; it's even easier now:

http://code.databio.org/GenomicDistributions/articles/01-intro.html

**Comment by nsheff** [comment]
I have this running now on dev.
