### ISSUE TITLE
cache retention policy and disclaimer

### ISSUE THREAD

**Issue by vpnagraj** [databio/LOLAweb#29]
how should we manage cache retention / do we need to include any disclaimer text about cache availability?

**Comment by nsheff** [comment]
let's add a disclaimer and cron job saying we'll delete them after 1 year.

**Comment by nmagee** [comment]
find /path/to/files* -mtime +365 -exec rm {} \;

The deletion cron job is now in place. I'll work with Pete on putting it in text on the about page.

**Comment by nmagee** [comment]
Some text is now in place on the ABOUT page, and so will work its way to the master branch. Closing this issue now.
