### ISSUE TITLE
Run summary stats

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#33]
Along with the UI decouple (https://github.com/databio/LOLAweb/issues/30) we should have the results page show some summary stats on the run:

- start time?
- end time?
- elapsed time?
- results URL
- filename uploaded
- genome selected
- universe selected
- database selected

anything else?

**Comment by nmagee** [comment]
I have a bit of an interest in capturing the users originating IP address.  That would let me do a bit of investigation on schools and campuses that are touching LOLA, but it’s not a burning hot priority.

**Comment by nsheff** [comment]
In tandem with #30

**Comment by vpnagraj** [comment]
i've taken a first pass at collecting / including run summary info (for an example see http://dev.lolaweb.databio.org/?key=OAV4E2X3L7YTPUW) 

@nmagee and @nsheff when you get a chance let me know what you think

**Comment by vpnagraj** [comment]
@nsheff good call ... only issue is that the table won't fit on the left side, so i'm using a text output instead:

http://dev.lolaweb.databio.org/?key=UDYOXT3MC1E2VF7

**Comment by nsheff** [comment]
Yeah, that makes sense. Unfortunately, the text output looks bad though, and introduces that horizontal scrollbar.

**Comment by vpnagraj** [comment]
ok another attempt (this time with the table transposed):

http://dev.lolaweb.databio.org/?key=UDYOXT3MC1E2VF7

**Comment by nsheff** [comment]
Yeah, that's what I was imagining!

**Comment by vpnagraj** [comment]
@nsheff 🔮 
@nmagee i'm punting on caching the ip address since it's not (yet) readily available in the shiny client data fields (https://github.com/rstudio/shiny/issues/141) ... that said, with google analytics i think we can get at some of that information

**Comment by nsheff** [comment]
The current table cuts off values on the right side (they don't quite fit in the left menu).
example, heres what I see:


Start | 2018-03-16 13:4
-- | --
End | 2018-03-16 13:4
Elapsed | 188 seconds
Cache | VAJOK1TQ3ME
Regions | lamina
Genome | hg19
Universe | activeDHS_univ
Database | Core


Maybe make it smaller text?? it needs to fit...

**Comment by vpnagraj** [comment]
now using `font-size:10px;` for run summary table, and also including commit hash from #59

**Comment by nsheff** [comment]
does that make it fit?

**Comment by nsheff** [comment]
looks fine to me now.
