### ISSUE TITLE
links

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#40]
let's add links to my lab page and to the source code. maybe let's change `Powered By SOMRC` to:

Powered By [SOMRC](https://somrc.virginia.edu/). A project from the [Sheffield lab](http://databio.org) at the University of Virginia. [Source code at GitHub](https://github.com/databio/LOLAweb).

or some variant thereof

**Comment by nsheff** [comment]
maybe also some note "run your own with a docker container" or something?

**Comment by vpnagraj** [comment]
just added links in b5c90ec
