### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#43]
the dev sever is returning a bad gateway at the moment.
Actually this just happend about 3 minutes ago; I had an interactive results tab open and it just choked.

**Comment by nsheff** [comment]
Something similar happened again just now... I was just clicking through the tabs on `dev` and got a "Disconnected" error.

**Comment by nmagee** [comment]
Checking on this...

**Comment by nsheff** [comment]
I believe this may happen when a new container is built on travis and pushed to the server; Can we ensure that new container builds don't destroy current sessions?

This is not a big deal, but just generally speaking it would be better that way

**Comment by nmagee** [comment]
@nsheff I'll check on the impacts of the `docker service update` call, and how respectful it is of working containers.  I think there's a "graceful" way to inject new containers into the swarm without killing sessions.

I'll get back to you here.

**Comment by nmagee** [comment]
I've implemented another flag in the `docker service update` calls that are hopefully a bit more gentle on image upgrades:

```
docker service update --update-delay 10s --stop-grace-period 180s --image $CONTAINER ssp_dev
```

It's the `--stop-grace-period` that is new. Let's keep an eye on it and see if that helps. So with this config, when a new Docker image is built, we wait 10 seconds between each new one being injected into the swarm, and we will wait up to 180 seconds for busy containers to stop their work.

**Comment by nmagee** [comment]
Closing this now. After killing the container and I was connected to, and letting a replacement spawn to the load balancer, I was able to get this error. I've not seen it appear at anytime other than around new image rollouts or when I am dropping DEV2 for maintenance. (Just when I would expect to see it.)
