### ISSUE TITLE
sample results link on front page

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#53]
with the change to tabs the 'sample results' link got moved to the "results" tab and is therefore no longer on the first page... that's fine, but I think we really need a link to sample results on the first page for first-time users. otherwise, they won't realize they can get there without runnign a complete analysis. nobody will think to click the 'run' tab.

we should add that link back in so it's in both places.

**Comment by vpnagraj** [comment]
ok the sample results link is back on the front page as of e426837
