### ISSUE TITLE
Submit button becomes active while processing

### ISSUE THREAD

**Issue by fhalbritter** [databio/LOLAweb#54]
The submit button ("Run LOLA") is deactivated upon submission (as it should be), but then seems to become activated again while the processing is still ongoing.

I've experienced this using my Firefox browser on Linux Mint with a fairly small input dataset. Seemed to happen about half a minute into processing, not sure whether at a specific stage.

**Comment by nsheff** [comment]
I can confirm that around the "calculating universe set overlaps", the RUN LOLA button becomes reactivated.

**Comment by vpnagraj** [comment]
thanks for raising this issue, i agree that's definitely confusing

i added a more comprehensive disabling (during run computation and while viewing cache) in 137dc1e

@nsheff those changes are live on dev if you'd like to have a look

**Comment by vpnagraj** [comment]
the fix for this issue is implemented on our dev server and will be trickling up to production in the near future
