### ISSUE TITLE
Unable to use own BED file

### ISSUE THREAD

**Issue by fhalbritter** [databio/LOLAweb#55]
I've first run LOLAweb using the example data provided, which worked fine. I then tried upload my own BED file (which the web interface tells me worked) and submitted that. The results I get, however, look the same as for the example data and the table at the bottom of the results page tells me that the userset "setB_100.bed" was used.

**Comment by nsheff** [comment]
Uh oh, that's a critical problem...

**Comment by nsheff** [comment]
I can confirm that the results are always showing example results, and never real results.

Here is an example run done with a different input bed file. it shows the example results output.

http://lolaweb.databio.org/?key=U8IARBLKXT1JDFC

**Comment by nsheff** [comment]
I am not sure what would cause this; Is this coming from this line? https://github.com/databio/LOLAweb/blob/0d346e7c86ea0e25af7207a1d3286a8f6f22b93f/apps/LOLAweb/app.R#L498

Possibly it thinks the cache is already loaded (because you've just tried the example one), so it doesn't load the new cache?

**Comment by nsheff** [comment]
I can confirm this problem is also on `dev`; and the cache key is correctly displayed in the database, yet the results are incorrect.

http://dev.lolaweb.databio.org/?key=8ODJMKWV3FC4RXQ

**Comment by nsheff** [comment]
Ok, the problem looks to be in the file upload; it is actually recalculating and re-caching the bad cache.

So somehow even if you upload a custom bed file, it's running lola on the example one, I think.

**Comment by nsheff** [comment]
The bug is in here:

`        if(!exampleuserset$toggle) {`

it is always just going to the example even when a user uploads a file

**Comment by nsheff** [comment]
`exampleuserset$toggle` is set to true no matter if the user has clicked "Browse for data to upload" or "load example data", so it doesn't matter what the user does, it always loads example data.

**Comment by nsheff** [comment]
The issue was that the toggle flag on the example data was set to TRUE, but the default was actually FALSE.

If you toggle the button a few times it will work; but if you just straight up try to upload your data, the incorrect default value kills it.

**Comment by nsheff** [comment]
I can confirm this is working now in dev.

**Comment by fhalbritter** [comment]
Sweet. Thanks for the rapid response
