### ISSUE TITLE
Errors for missing pieces should suggest rerunning the cache.

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#56]
What happens if someone who ran LOLAweb with an old version tries to load that cache with an updated LOLAweb?

Well, the old versionw ill lack a few components from the new. If you run a cache in an older version of LOLA web, then try to load it in a new version, missing components give you an error like this:

`Error: An error has occurred. Check your logs or contact the app author for clarification.`

I think this should be a more informative message, if the requested object is simply not found  (it could suggest re-running the cache for example).

If there truly was an error then it's fine to say that, otherwise, I think that's not the right message to send.

**Comment by nsheff** [comment]
Related to #66

**Comment by nsheff** [comment]
@vpnagraj this comes up again with the new genomic distributions plot, which doesn't show up for sample data.

**Comment by vpnagraj** [comment]
i believe #66 and #101 now encompass this issue

closing this for now ... we can always reopen if needed
