### ISSUE TITLE
display commit hash for version

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#59]
Right now it's hard to tell when an update has propogated to production containers. I propose the web page display the commit hash of LOLAweb

We would just have to use git to grab the latest hash commit of whatever we pulled down in the LOLAweb container, using for example something like this:

https://github.com/databio/pypiper/blob/f88d2a68fef1014e4e8a1294c8d57a5ceeb5a747/pypiper/manager.py#L411

So the LOLAweb R code would just, upon running, run a system command `git rev-parse` to grab the hash, and display this in the footnotes.

**Comment by nsheff** [comment]
further, this has should be stored with the results as metadata.

This is related to #56 and #33

**Comment by vpnagraj** [comment]
this is incorporated in b53344733 ... let me know if that's what you had in mind

**Comment by nsheff** [comment]
also let's call it LOLAweb version commit or something...
