### ISSUE TITLE
hg38  -- disconnected from server

### ISSUE THREAD

**Issue by fhalbritter** [databio/LOLAweb#62]
I keep getting "Disconnected from the server" errors with the hg38 reference.

This happens when I try to run LOLA: I switch the reference to hg38 and upload my BED file, keeping all other options at default, then click "Run". I'm told it's loading the data then switches to "timing stopped" immediately and displays the "disconnected from server" error.

It works with the same file and hg19, so I suppose something's off with the reference caches.

Overall, more informative error messages might help from a usability perspective.

**Comment by nsheff** [comment]
Yes, I am seeing the same behavior.

**Comment by vpnagraj** [comment]
@fhalbritter thanks so much for raising this issue ... i'm on it!

@nsheff fyi i think this is an issue with `read.table` for the universe (seems to be working with `readBed`) just pushed a change to dev (1025a13 ) please have a look when you get a chance

**Comment by nsheff** [comment]
yeah that does solve the problem for me. this is a critical error so I think we should go ahead and release this to master.

**Comment by nsheff** [comment]
On the error message side-issue -- @vpnagraj can you think of a way to report better error messages more generally?

**Comment by vpnagraj** [comment]
@fhalbritter thanks again for bringing this to our attention, the problem should be resolved now

i'll open a new issue regarding the suggestion for more informative error messages
