### ISSUE TITLE
move download plot buttons

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#69]
The *download plot* buttons should be replaced by smaller icons that can be displayed next to the title (maybe in front of it) instead of below it, which adds a lot of unused whitespace.

**Comment by vpnagraj** [comment]
plot buttons now read "PDF" to free up space

**Comment by nsheff** [comment]
No the point was to save vertical space; this text change didn't save any useful space... they need to be moved up a line.

**Comment by vpnagraj** [comment]
ok ... buttons are now side-by-side with headers

**Comment by nsheff** [comment]
looks great!
