### ISSUE TITLE
consider setting a max number of rows that can be returned for plots

### ISSUE THREAD

**Issue by vpnagraj** [databio/LOLAweb#71]
currently depending on how you modify the sliders / cutoffs, the number of rows returned can be unwieldy ... this is ok for tables but plotting  and interpretation of plots can be difficult

we might consider setting a maximum for the number of rows that can be plotted ...

**Comment by nsheff** [comment]
for the scatterplot, might look into the hexbin plots to avoid plotting every point; then just plot the actual points for the ones not filtered by the sliders.

**Comment by vpnagraj** [comment]
histograms are capped at 50 results as of 5d48e5b

@nsheff can you test this and confirm it's working as you had in mind?

**Comment by nsheff** [comment]
yes I noticed this. looks great.
