### ISSUE TITLE
permissions to logs

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#73]

**Comment by nsheff** [comment]
I lack permissions to shiny logs

~/lola-data/shinylog$ cat LOLAweb-shiny-20180413-170625-33231.log
cat: LOLAweb-shiny-20180413-170625-33231.log: Permission denied

**Comment by nmagee** [comment]
@nsheff you should have read access to these now, I added you to the `lolaweb` group.

**Comment by nsheff** [comment]
thanks
