### ISSUE TITLE
loading delay

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#75]
on both production and dev, there's now about a 5-10 second delay between when the page loads and populates half of the inputs, and then a red error is displayed for a split second, and then things load completely.
I am not sure what is causing this delay.

**Comment by vpnagraj** [comment]
no idea ... but i noticed this only after the changes to how the sample data / universes / databases were mounted to the containers

so i'm not sure if there's a "bug to fix" here with the shiny app ... @nmagee any ideas?

**Comment by nsheff** [comment]
I think I figured it out...

**Comment by nsheff** [comment]
It's because I'm now included non-cached databases, and `list.files` is choking on listing through thousands of files.
it's better with this fix, as it can handle big databases without problem.

**Comment by vpnagraj** [comment]
nice!
