### ISSUE TITLE
examples should auto-populate their reference genomes

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#76]
we can't run an hg19 sample on an mm10 database.

2 solutions: when you choose a sample, it populates the appropriate genome; or
when you pick a genome, it restricts the dropdown to samples for that genome.

I've started to implement these but reached my limit as I don't know how to find the `input` variable. @vpnagraj ?

**Comment by vpnagraj** [comment]
i started on this went with option two:

> when you pick a genome, it restricts the dropdown to samples for that genome

that seems to be working (in the sense that i can see the 2 bed files in `hg19/` when i select hg19) ... but when i try to run a job i'm getting an error

@nsheff can you double check the permissions on those example files? maybe similar to what we were seeing in #50 yesterday?

also wondering if we will have example usersets for *all* of the reference genomes?

**Comment by nsheff** [comment]
Yep, permissions fixed it.
That is great, thanks. This works.

I'll make sure to add examples for all of the reference genomes.

**Comment by vpnagraj** [comment]
@nsheff have you successfully completed a run with either of the example user sets? 

i see that they load and start processing but i get disconnected at the end (when the cache is being created)

maybe also related to discussion in #50 and how the cache dir is being mounted on containers? is shiny not able to write to that location?

**Comment by nsheff** [comment]
yes, they are working for me.

I just depends on if you got a container that's correctly mounting `cache`. it's exactly #50, looks like you're assigned to the bad containers now and I got the good ones.
