### ISSUE TITLE
scatterplot visualization problems

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#77]
The top is cut off of the scatterplot.  this is actually cutting off some of the points, and the legend

there is also no scale on the x axis.

**Comment by nsheff** [comment]
see this for example:

http://dev.lolaweb.databio.org/?key=G1CIYJS2NLX7PEU

**Comment by vpnagraj** [comment]
i think 3f05b6a did the trick for the legend

http://dev.lolaweb.databio.org/?key=F1NJU8KSWI59H4E

**Comment by nsheff** [comment]
yep. but in the lamina example, the one hit is still not showing up. do you know why?

**Comment by vpnagraj** [comment]
yeah and i'm seeing the same issue for the CD14 example file

maybe this has something to do with #51 (the pvalue sliders have `NaN`)?

**Comment by vpnagraj** [comment]
ok changes are live on dev to accommodate infinite log p values (p=0, complete overlap) and infinite odds ratios (from running two query sets with a restricted universe built on those same regions)

all values are plotted in the scatterplot ... but for infinite log p values the value is set to the max log pval+1 (on hover it says infinite):

http://dev.lolaweb.databio.org/?key=G1CIYJS2NLX7PEU

for an infinite odds ratio, the value is set to a little less than 0 (on hover it says NA):

http://dev.lolaweb.databio.org/?key=L32PDX1ERHTAMYO

@nsheff i'm going to close this now, feel free to re-open if you have other suggestions
