### ISSUE TITLE
mm9 failing

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#82]
```
Combining...
I don't have data for reference assembly mm9
```
We have LOLA resources for `mm9` but because GenomicDistributions lacks this so far, I realized it's causing the whole thing to fail.

@vpnagraj can you make it so the genomic distribution plots are not catastrophic if they fail? So it can still show the LOLA results?

https://github.com/databio/GenomicDistributions/issues/2

I will work on adding `mm9` to GD but in this is generally useful that it should show whatever it can without failing catastrophically.

**Comment by nsheff** [comment]
I just released v0.5 of [Genomic Distributions](https://github.com/databio/GenomicDistributions), which includes mm9 data.

**Comment by nsheff** [comment]
> basically skips the genomic distributions processing if the genome isn't in utils::data(package="GenomicDistributions")$results[,"Item"] for TSS, chromeSize, geneModels respectively ... if any or all of those are present, then the data is processed accordingly and plot(s) will appear

Now that I think about this, a better approach would be to just wrap this processing in a `tryCatch`, because the current method relies on the way GenomicDistributions is internally doing things, which is not guaranteed. No need to peer into that package's inner workings, just make it so if those tasks fail, they fail gracefully by just not printing failed plots. This method is easier to implement, easier to maintain, and more robust to changes in the other package.

**Comment by nsheff** [comment]
did we ever pull 0.5 of GenomicDistributions into this? Because my `mm9` run is still not displaying those plots...
(it is not failing, which means the above fix succeeded).

**Comment by vpnagraj** [comment]
as of now, we are using the most recent version GenomicDistributions and mm9 is no longer failing

closing this issue as it speaks to a slightly different improvement that we can make that is covered in #101
