### ISSUE TITLE
missing plots should display a message

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#88]
right now mm9 runs aren't showing all genomic distribution plots (See #82). They are just blank. can we make them at least say a message if there is something missing?

This is more a universal, forward thinking thing...when we add new plots, they should never really just be blank. there should be some function that inserts at least a generic placeholder message about "cannot display" or something...

**Comment by vpnagraj** [comment]
missing plots display message as of e5b7098

this speaks to another issue with how processing handles errors (that result in missing output), which will be addressed in #101 moving forward
