### ISSUE TITLE
mm10 is broken

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#89]
it's giving this error:
```
::Loading cache::       /mnt/q/shefflab/LOLAweb/databases//LOLACore/mm10/encodeTFBSmm10/encodeTFBSmm10.RData
Timing stopped at: 4.916 0.044 4.984
Warning: Error in combine_CompressedList_objects: the objects to combine must be CompressedList objects (or NULLs)
Stack trace (innermost first):
    96: combine_CompressedList_objects
    95: .local
    94: c
    93: c
    92: readRegionGRL
    91: loadRegionDB
    90: system.time [/srv/shiny-server/LOLAweb/apps/LOLAweb/app.R#578]
    89: eventReactiveHandler [/srv/shiny-server/LOLAweb/apps/LOLAweb/app.R#509]
    69: rawdat_nocache
    68: withCallingHandlers [/srv/shiny-server/LOLAweb/apps/LOLAweb/app.R#385]
    67: observeEventHandler [/srv/shiny-server/LOLAweb/apps/LOLAweb/app.R#382]
     1: runApp
Warning: Error in combine_CompressedList_objects: the objects to combine must be CompressedList objects (or NULLs)
Stack trace (innermost first):
    61: <Anonymous>
    60: stop
    59: rawdat_nocache
    58: observerFunc [/srv/shiny-server/LOLAweb/apps/LOLAweb/app.R#753]
     1: runApp

```

**Comment by nsheff** [comment]
Something wrong with that cache, I think...

```
docker run --rm -it --volume /mnt/q:/mnt/q databio/lolaweb bash
R
LOLA::loadRegionDB("/mnt/q/shefflab/LOLAweb/databases//LOLACore/mm10/")"
```

**Comment by nsheff** [comment]
I am trying regenerating the cache now.

**Comment by nsheff** [comment]
that didn't work. it may be a LOLA version thing. can we try updating the dev container to the latest R/bioconductor/LOLA version?

**Comment by nsheff** [comment]
turns out it's not a LOLA version problem, but could be a GenomicRanges version problem. I still think we should update...

**Comment by vpnagraj** [comment]
ok yeah i think the shinyBase container image we are pulling should include the bioconductor (not github) version of LOLA: 

https://github.com/databio/shinyBase/blob/master/Dockerfile#L29

that gets pulled in via the LOLAweb dockerfile ... but i can't remember if that base image gets rebuilt automatically? every time we push a change to databio/shinyBase ? manually? 

@nmagee is going to get sick of explaining this to me :)

**Comment by nsheff** [comment]
it only gets rebuilt if we push a change to databio/shinyBase or trigger it manually.

**Comment by nsheff** [comment]
Ok, I rebuilt it locally and pushed changes -- can we trigger a re-deploy of the containers @nmagee to see if this solves the problem?

**Comment by nmagee** [comment]
Hey, just getting home and seeing this message. Yes I’ll go ahead and do a new pull and redeploy.

Neal


On Jul 6, 2018, at 4:17 PM, Nathan Sheffield <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I rebuilt it locally and pushed changes -- can we trigger a re-deploy of the containers @nmagee<https://github.com/nmagee> to see if this solves the problem?

**Comment by nmagee** [comment]
Since you rebuilt the shinyBase container and pushed it up to Docker Hub, I just went to the TravisCI page for LOLAweb and triggered the rebuild there. That actually sends an SQS message that will spawn them out onto the servers in a seamless way.

I’m seeing the new Dev containers up and running there now. Can one of you guys verify that your fix is in place and working okay?

N

**Comment by nsheff** [comment]
Yes, that worked! So, turns out I was right, it was probably some kind GRanges version issue. it's working now on mm10.

@nmagee thanks for redeploy -- at some point can you write down some brief instructions or a link somewhere so that in the future I don't have to bother you to do that? I forgot we were using travis for those builds and that was the way to rebuild it...
