### ISSUE TITLE
reference universes

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#9]
universes are actually relative to a reference assembly, like databases.

hence, we should move the selection of assembly to the left, with the input, and this will need to populate options select boxes for both universe and database.

in other words, activeDHS universe will not work with an mm9 database.

**Comment by nsheff** [comment]
@vpnagraj  I have now organized some additional universes under `universes` now by reference genome; please populate this select box according to the subdirectory on-the-fly depending on selection in the reference genome drop-down.

**Comment by vpnagraj** [comment]
@nsheff sounds good ... i see them in there and will start working on implementing that in the app

**Comment by nsheff** [comment]
along the same lines, let's do `references `similarly.
I've updated the reference databases now; can you also populate these based on the ref genome selected? and make it a select box? this can then populate automatically based on whatever we stick in that folder

**Comment by vpnagraj** [comment]
@nsheff just to be clear "reference databases" = region databases? 

and i'm now seeing `Core/`, `LOLAJaspar` and `LOLARoadmap` as the dirs under reference ... those should be the options available in a dropdown select list based on whether or not the user has selected a reference genome that present in one (or more) of those DBs?

**Comment by nsheff** [comment]
> just to be clear "reference databases" = region databases?
Yes.

> those should be the options available in a dropdown select list based on whether or not the user has selected a reference genome that present in one (or more) of those DBs
Yes

**Comment by vpnagraj** [comment]
should be done as of a35370a

**Comment by nsheff** [comment]
yep this looks great. now it's just up to me to populate those folders well.
