### ISSUE TITLE
docker instructions are confusing

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#90]
Noticed while trying to solve #89 --

our docs never mention the `shinybase` container, or instructions for building it.

I think probably our docs didn't get updated from the split out of shinybase?

**Comment by nmagee** [comment]
Now [documented](https://github.com/databio/LOLAweb/blob/21bd8ffaeb7bae5aa04310628300c3067dcb2105/README.md?plain=1#L15) in the README.
