### ISSUE TITLE
Always "Disconnected from the server." when using mm10

### ISSUE THREAD

**Issue by holgerbrandl** [databio/LOLAweb#96]
The web-UI is always giving this error when selecting mm10 as reference

![image](https://user-images.githubusercontent.com/200952/46296435-a9d8e700-c59a-11e8-9a63-c318ecc815be.png)

I don't know the precise timing, but it seems to happen before starting "Calculating universe set overlaps..."

If I use the same input (and process them with mm10) it goes through without any problem (except for sure that it's the wrong species). You can my example data set under https://cloud.mpi-cbg.de/index.php/s/KgXvVkohySFzTOY

**Comment by vpnagraj** [comment]
@holgerbrandl thank you again for reaching out about this problem

we've just issued a 1.3.0 release that fixes this issue ... so the production site should work with mm10 bed files now as well:

http://lolaweb.databio.org/?key=IHQ9P43EJ5DOWXS
