### ISSUE TITLE
Download buttons are broken in dev-version

### ISSUE THREAD

**Issue by holgerbrandl** [databio/LOLAweb#97]
Following up on #96 I've used the dev instance under http://dev.lolaweb.databio.org which provides online-results, but all download buttons (individual as well as "download all plots") just give a server error 
![image](https://user-images.githubusercontent.com/200952/46348399-2fb66a00-c64f-11e8-9939-dac6d8be9aff.png)

E.g. http://dev.lolaweb.databio.org/session/a35770074b51f27ec6ce77160330bf97/download/oddsratio_plot_dl?w=
Just gives the error "ERROR: An error has occurred. Check your logs or contact the app author for clarification."

Btw, the csv download link under "Tables" works fine.

**Comment by vpnagraj** [comment]
thanks for raising this issue, i believe i've addressed the problem and individual download buttons for plots (and the "download all plots" button) are working on dev
